// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe/tasks/cc/core/proto/base_options.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mediapipe.Tasks.Core.Proto {

  /// <summary>Holder for reflection information generated from mediapipe/tasks/cc/core/proto/base_options.proto</summary>
  public static partial class BaseOptionsReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe/tasks/cc/core/proto/base_options.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BaseOptionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjBtZWRpYXBpcGUvdGFza3MvY2MvY29yZS9wcm90by9iYXNlX29wdGlvbnMu",
            "cHJvdG8SGm1lZGlhcGlwZS50YXNrcy5jb3JlLnByb3RvGjBtZWRpYXBpcGUv",
            "dGFza3MvY2MvY29yZS9wcm90by9hY2NlbGVyYXRpb24ucHJvdG8aMW1lZGlh",
            "cGlwZS90YXNrcy9jYy9jb3JlL3Byb3RvL2V4dGVybmFsX2ZpbGUucHJvdG8i",
            "rAEKC0Jhc2VPcHRpb25zEj0KC21vZGVsX2Fzc2V0GAEgASgLMigubWVkaWFw",
            "aXBlLnRhc2tzLmNvcmUucHJvdG8uRXh0ZXJuYWxGaWxlEh4KD3VzZV9zdHJl",
            "YW1fbW9kZRgCIAEoCDoFZmFsc2USPgoMYWNjZWxlcmF0aW9uGAMgASgLMigu",
            "bWVkaWFwaXBlLnRhc2tzLmNvcmUucHJvdG8uQWNjZWxlcmF0aW9uQjkKJWNv",
            "bS5nb29nbGUubWVkaWFwaXBlLnRhc2tzLmNvcmUucHJvdG9CEEJhc2VPcHRp",
            "b25zUHJvdG8="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mediapipe.Tasks.Core.Proto.AccelerationReflection.Descriptor, global::Mediapipe.Tasks.Core.Proto.ExternalFileReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mediapipe.Tasks.Core.Proto.BaseOptions), global::Mediapipe.Tasks.Core.Proto.BaseOptions.Parser, new[]{ "ModelAsset", "UseStreamMode", "Acceleration" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Base options for mediapipe tasks.
  /// Next Id: 4
  /// </summary>
  public sealed partial class BaseOptions : pb::IMessage<BaseOptions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BaseOptions> _parser = new pb::MessageParser<BaseOptions>(() => new BaseOptions());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BaseOptions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mediapipe.Tasks.Core.Proto.BaseOptionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseOptions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseOptions(BaseOptions other) : this() {
      _hasBits0 = other._hasBits0;
      modelAsset_ = other.modelAsset_ != null ? other.modelAsset_.Clone() : null;
      useStreamMode_ = other.useStreamMode_;
      acceleration_ = other.acceleration_ != null ? other.acceleration_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseOptions Clone() {
      return new BaseOptions(this);
    }

    /// <summary>Field number for the "model_asset" field.</summary>
    public const int ModelAssetFieldNumber = 1;
    private global::Mediapipe.Tasks.Core.Proto.ExternalFile modelAsset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.Tasks.Core.Proto.ExternalFile ModelAsset {
      get { return modelAsset_; }
      set {
        modelAsset_ = value;
      }
    }

    /// <summary>Field number for the "use_stream_mode" field.</summary>
    public const int UseStreamModeFieldNumber = 2;
    private readonly static bool UseStreamModeDefaultValue = false;

    private bool useStreamMode_;
    /// <summary>
    /// Whether the mediapipe task treats the input data as a continuous data
    /// stream, or a batch of unrelated data. Default to False.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UseStreamMode {
      get { if ((_hasBits0 & 1) != 0) { return useStreamMode_; } else { return UseStreamModeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        useStreamMode_ = value;
      }
    }
    /// <summary>Gets whether the "use_stream_mode" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUseStreamMode {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "use_stream_mode" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUseStreamMode() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "acceleration" field.</summary>
    public const int AccelerationFieldNumber = 3;
    private global::Mediapipe.Tasks.Core.Proto.Acceleration acceleration_;
    /// <summary>
    /// Acceleration setting to use available delegate on the device.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mediapipe.Tasks.Core.Proto.Acceleration Acceleration {
      get { return acceleration_; }
      set {
        acceleration_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BaseOptions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BaseOptions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ModelAsset, other.ModelAsset)) return false;
      if (UseStreamMode != other.UseStreamMode) return false;
      if (!object.Equals(Acceleration, other.Acceleration)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (modelAsset_ != null) hash ^= ModelAsset.GetHashCode();
      if (HasUseStreamMode) hash ^= UseStreamMode.GetHashCode();
      if (acceleration_ != null) hash ^= Acceleration.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (modelAsset_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ModelAsset);
      }
      if (HasUseStreamMode) {
        output.WriteRawTag(16);
        output.WriteBool(UseStreamMode);
      }
      if (acceleration_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Acceleration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (modelAsset_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ModelAsset);
      }
      if (HasUseStreamMode) {
        output.WriteRawTag(16);
        output.WriteBool(UseStreamMode);
      }
      if (acceleration_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Acceleration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (modelAsset_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ModelAsset);
      }
      if (HasUseStreamMode) {
        size += 1 + 1;
      }
      if (acceleration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Acceleration);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BaseOptions other) {
      if (other == null) {
        return;
      }
      if (other.modelAsset_ != null) {
        if (modelAsset_ == null) {
          ModelAsset = new global::Mediapipe.Tasks.Core.Proto.ExternalFile();
        }
        ModelAsset.MergeFrom(other.ModelAsset);
      }
      if (other.HasUseStreamMode) {
        UseStreamMode = other.UseStreamMode;
      }
      if (other.acceleration_ != null) {
        if (acceleration_ == null) {
          Acceleration = new global::Mediapipe.Tasks.Core.Proto.Acceleration();
        }
        Acceleration.MergeFrom(other.Acceleration);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (modelAsset_ == null) {
              ModelAsset = new global::Mediapipe.Tasks.Core.Proto.ExternalFile();
            }
            input.ReadMessage(ModelAsset);
            break;
          }
          case 16: {
            UseStreamMode = input.ReadBool();
            break;
          }
          case 26: {
            if (acceleration_ == null) {
              Acceleration = new global::Mediapipe.Tasks.Core.Proto.Acceleration();
            }
            input.ReadMessage(Acceleration);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (modelAsset_ == null) {
              ModelAsset = new global::Mediapipe.Tasks.Core.Proto.ExternalFile();
            }
            input.ReadMessage(ModelAsset);
            break;
          }
          case 16: {
            UseStreamMode = input.ReadBool();
            break;
          }
          case 26: {
            if (acceleration_ == null) {
              Acceleration = new global::Mediapipe.Tasks.Core.Proto.Acceleration();
            }
            input.ReadMessage(Acceleration);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
